import builtins from "builtin-modules";
import { Command } from "commander";
import dotenv from "dotenv";
import esbuild from "esbuild";
import * as fs from "fs";
import * as path from "path";
import process from "process";
import packageJson from "./package.json" with { type: "json" };
import manifest from "./manifest.json" with { type: "json" };

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin: ${packageJson.repository}
*/
`;

function cleanOutdir(outdir) {
	if (fs.existsSync(outdir)) {
		fs.rm(outdir, { recursive: true });
	}
}

dotenv.config();

const program = new Command();
program
	.option("-p, --production", "Production build")
	.option("-v, --vault", "Use vault path")
	.option("-o, --output-dir <path>", "Output path")
	.option("-b, --beta", "Pre-release version")
	.parse();
program.parse();

/** OPTIONS */
const opt = program.opts();
const prod = opt.production ?? false;
const exportToVault = opt.vault ?? false;

/** VARIABLES **/
const isStyled = fs.existsSync("src/styles.css");
const pluginID = manifest.id;

/** FOLDER PATHS **/
const vaultPath = process.env.VAULT;
const folderPlugin = vaultPath
	? path.join(vaultPath, ".obsidian", "plugins", pluginID)
	: undefined;

if (vaultPath && exportToVault && !fs.existsSync(folderPlugin)) {
	fs.mkdirSync(folderPlugin, { recursive: true });
}
if (opt.beta && !fs.existsSync("manifest-beta.json")) {
	fs.copyFileSync("manifest.json", "manifest-beta.json");
}

let outdir = "./";
if (opt.outputDir) {
	outdir = opt.outputDir;
	cleanOutdir(outdir);
} else if (exportToVault) {
	outdir = folderPlugin;
	if (!prod) fs.writeFileSync(path.join(folderPlugin, ".hotreload"), "");
} else if (prod) {
	outdir = "./dist";
	//clean dist if
	cleanOutdir(outdir);
}

/**
 * Move styles.css to output directory
 */
const moveStyles = {
	name: "move-styles",
	setup(build) {
		build.onEnd(() => {
			fs.copyFileSync("src/styles.css", "./styles.css");
		});
	},
};

/**
 * Export to vault if set in environment variable
 */
const exportToVaultFunc = {
	name: "export-to-vault",
	setup(build) {
		build.onEnd(() => {
			if (!folderPlugin)
				throw new Error("VAULT environment variable not set, skipping export to vault");

			fs.copyFileSync(`${outdir}/main.js`, path.join(folderPlugin, "main.js"));
			if (fs.existsSync(`${outdir}/styles.css`))
				fs.copyFileSync("./styles.css", path.join(folderPlugin, "styles.css"));
			if (opt.beta) fs.copyFileSync("manifest-beta.json", path.join(folderPlugin, "manifest.json"));
			else fs.copyFileSync("./manifest.json", path.join(folderPlugin, "manifest.json"));
		});
	},
};

/**
 * Export to production folder
 */
const exportToDist = {
	name: "export-to-dist",
	setup(build) {
		build.onEnd(() => {
			if (opt.beta) fs.copyFileSync("manifest-beta.json", path.join(outdir, "manifest.json"));
			else fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
		});
	},
};

/**
 * ENTRIES *
 */
const entryPoints = ["src/main.ts"];
if (isStyled) entryPoints.push("src/styles.css");

/** PLUGINS **/
const plugins = [];
if (isStyled) plugins.push(moveStyles);
if (prod) plugins.push(exportToDist);
if (prod && exportToVault) plugins.push(exportToVaultFunc);

/**
 * BUILD
 */
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints,
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "esnext",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minifySyntax: prod,
	minifyWhitespace: prod,
	outdir,
	plugins,
});

if (prod) {
	console.log("🎉 Build for production");
	console.log(`📤 Output directory: ${outdir}`);
	await context.rebuild();
	console.log("✅ Build successful");
	process.exit(0);
} else {
	console.log("🚀 Start development build");
	console.log(`📤 Output directory: ${outdir}`);
	await context.watch();
}
