allowBuilds:
  "@codemirror/language": true
  '@codemirror/language@https://codeload.github.com/lishid/cm-language/tar.gz/b817e72a9861b3f8a50a92a2ea53cbafc4f88eb3': true
  classic-level: true
  core-js: true
  edgedriver: true
  electron: true
  esbuild: true
  geckodriver: true
  obsidian-typings: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - svelte@3.49.0 || 3.59.2 || 4.2.19 || 5.51.5 || 5.53.5 || 5.55.7
  - json5@1.0.2
  - cross-spawn@6.0.6
  - mermaid@11.10.0 || 11.14.1
  - serialize-javascript@7.0.3 || 7.0.5
  - lodash-es@4.17.23 || 4.17.24
  - electron@39.8.0 || 39.8.1 || 39.8.3 || 39.8.4 || 39.8.5
  - babel-traverse@7.23.2
  - uuid@11.1.1
  - ts-deepmerge@8.0.0
