allowBuilds:
  "@codemirror/language": true
  '@codemirror/language@https://codeload.github.com/lishid/cm-language/tar.gz/b817e72a9861b3f8a50a92a2ea53cbafc4f88eb3': true
  classic-level: true
  core-js: true
  edgedriver: true
  electron: true
  esbuild: true
  geckodriver: true
  obsidian-typings: true
blockExoticSubdeps: false
