name: "Feature request"
description: Suggest an idea for the obsidian GitHub Publisher plugin.
title: "[FR]: "
labels: ["✨ Enhancement"]
assignees:
  - lisandra-dev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for this report!
        
        ## Contacts
        - [Discord](https://discord.gg/6DyY779Nbn): Have some ressource for user, bug resolve and quick communication about update and bug.
        - Mail: lisandra-dev@yahoo.com
        
  - type: checkboxes
    attributes:
      label: Issue validation
      description: "Thanks to check if your issue is relative to the repository. Any non relative or duplicate issue will be closed."
      options:
        - label: "I checked the issue to prevent duplicate"
          required: true
  - type: textarea
    id: describe-request
    attributes:
      label: Is your feature related to a problem ?
      description: If you found a solution with the inherent limit I had with Obsidian, please, add it here! 
      placeholder: "Tell me the original problem"
  - type: textarea
    id: describe-solution
    attributes:
      label: What solution do you want to see ?
      description: Describe your idea here!
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe the alternative you've considered
  - type: dropdown
    id: version
    attributes:
      label: OS
      description: What OS do you use ? 
      multiple: true
      options:
        - IOS
        - Android
        - MacOS
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    attributes:
      label: Plugin version
      description: What version of the plugin do you use ?
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Obsidian version & debug log
      description: Please, add the Obsidian version and the debug log here, using the obsidian commands `show debug log`
      render: bash session
    validations:
      required: true
