name: "[Mkdocs Publisher Template] Feature request"
description: Suggest an idea for the publisher mkdocs template.
title: "[FR]: "
labels: ["enhancement", "Material Mkdocs Template"]
assignees:
  - lisandra-dev
body:
  - type: markdown
    id: info-user
    attributes:
      value: |
        Thanks for this report!
  - type: checkboxes
    attributes:
      label: Issue validation
      description: "Thanks to check if your issue is relative to the repository. Any non relative or duplicate issue will be closed."
      options:
        - label: "My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)"
          required: true
        - label: "I checked the issue to prevent duplicate"
          required: true
  - type: textarea
    id: describe-request
    attributes:
      label: Is your feature related to a problem ?
      description: If you found a solution with the inherent limit I had with Obsidian, please, add it here!
      placeholder: "Tell me the original problem"
  - type: textarea
    id: describe-solution
    attributes:
      label: What solution do you want to see ?
      description: Describe your idea here!
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe the alternative you've considered
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

