name: Auto-merge translation PR
on:
    pull_request_target:
        types:
          - opened
          - synchronize
          - reopened
          - edited
          - labeled
          - unlabeled
          - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'i18n')
    steps:
      - uses: pascalgn/automerge-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "ci(i18n): auto-merge translation"
          MERGE_LABELS: ""
          
          